name: Portal Warfare
main: com.ftwinston.KillerMinecraft.Modules.PortalWarfare.Plugin
depend: [Killer Minecraft]
version: 1
load: STARTUP
description: A game mode for Killer Minecraft
author: FTWinston